// =============================================================================
// conv_engine_tb.v  --  self-checking testbench for the 3x3 convolution engine.
//
// The testbench OWNS its stimulus: it reads the golden stream/expected files,
// drives the DUT's i_valid/i_data input stream, samples the o_valid/o_data
// output stream, and compares to the expected words. It does NOT reach into the
// DUT (no hierarchical access), so it runs identically under both simulators
// (Icarus, Verilator). Prints exactly one summary line ("RESULT: PASS" or
// "RESULT: FAIL") so the Makefiles can grep for pass/fail (course convention).
// Dumps a VCD to sim/conv_engine.vcd for GTKWave.
//
// Files (generated by tools/gen_golden.py, read at run time):
//   golden/conv_stim.hex   input stream  : N_CASES * (KCNT + ICNT) words
//   golden/conv_exp.hex    expected out  : N_CASES * NPIX words
//   golden/conv_count.vh   N_CASES, KCNT, ICNT, NPIX (generated localparams)
//
// The SAME testbench drives the synthesized gate-level netlist (gl-sim), so the
// netlist must keep the conv_engine port list intact.
// =============================================================================
`timescale 1ns/1ps

module conv_engine_tb;
    localparam integer WIDTH = 16;
    localparam integer FRAC  = 10;
    localparam integer IMG   = 8;
    // Clock half-period (ns). RTL/functional gate sim are zero/unit-delay, so the
    // default 5 (10 ns) is fine. The SDF timing sim (03_GATE gl-sim-sdf) overrides
    // this with -DCLK_HALF=25 so the clock is slower than the real cell delays
    // (the SRAM->MAC path needs ~41 ns), otherwise timing violations corrupt data.
`ifndef CLK_HALF
 `define CLK_HALF 5
`endif
`include "conv_count.vh"               // N_CASES, KCNT, ICNT, NPIX (generated)

    localparam integer NIN     = KCNT + ICNT;      // words streamed in per case
    localparam integer TIMEOUT = 100000;

    reg                     clk = 1'b0;
    reg                     rst_n;
    reg                     i_valid;
    reg  signed [WIDTH-1:0] i_data;
    wire                    o_valid;
    wire signed [WIDTH-1:0] o_data;
    wire                    o_done;
    wire                    o_busy;

    // The synthesized GATE netlist has no parameters (synthesis resolves them to
    // constants), so only pass parameter overrides for RTL sim. For gate sim
    // (GL_NETLIST defined by 03_GATE, both the functional and SDF variants)
    // instantiate plainly -- the netlist bakes in WIDTH=16/FRAC=10/IMG=8, which
    // match the localparams above.
`ifdef GL_NETLIST
    conv_engine dut (
`else
    conv_engine #(.WIDTH(WIDTH), .FRAC(FRAC), .IMG(IMG)) dut (
`endif
        .clk(clk), .rst_n(rst_n),
        .i_valid(i_valid), .i_data(i_data),
        .o_valid(o_valid), .o_data(o_data), .o_done(o_done), .o_busy(o_busy)
    );

    // Timing-annotated gate sim: 03_GATE's gl-sim-sdf passes -DSDF_FILE=... and
    // builds the cell models WITH delays (no UNIT_DELAY) so these SDF cell-arc
    // delays take effect. (Functional gl-sim leaves SDF_FILE undefined.)
`ifdef SDF_FILE
    initial $sdf_annotate(`SDF_FILE, dut);
`endif

    // testbench-owned golden memories
    reg [WIDTH-1:0] stim [0:N_CASES*NIN-1];
    reg [WIDTH-1:0] exp  [0:N_CASES*NPIX-1];
    reg [WIDTH-1:0] got  [0:NPIX-1];               // collected outputs (one case)

    integer cse, i, k, errors, ngot, cyc;

    always #(`CLK_HALF) clk = ~clk;

    initial begin
        $dumpfile("sim/conv_engine.vcd");
        $dumpvars(0, conv_engine_tb);
    end

    // ---- drive one case's input stream, collect its NPIX outputs ----
    task run_case(input integer c);
        integer j;
        begin
            // reset the engine before each case (synchronous, active-low)
            rst_n   = 1'b0;
            i_valid = 1'b0;
            i_data  = {WIDTH{1'b0}};
            @(negedge clk); @(negedge clk);
            rst_n = 1'b1;

            // stream KCNT kernel words then ICNT image words, one per clock
            for (j = 0; j < NIN; j = j + 1) begin
                @(negedge clk);
                i_valid = 1'b1;
                i_data  = stim[c*NIN + j];
            end
            @(negedge clk);
            i_valid = 1'b0;
            i_data  = {WIDTH{1'b0}};

            // collect NPIX outputs: sample o_data on every cycle o_valid is high
            ngot = 0;
            cyc  = 0;
            while (ngot < NPIX && cyc < TIMEOUT) begin
                @(posedge clk);
                #1;
                if (o_valid) begin
                    got[ngot] = o_data;
                    ngot = ngot + 1;
                end
                cyc = cyc + 1;
            end
        end
    endtask

    initial begin
        errors = 0;
        // initialize golden memories to a known value, then load
        for (i = 0; i < N_CASES*NIN;  i = i + 1) stim[i] = {WIDTH{1'b0}};
        for (i = 0; i < N_CASES*NPIX; i = i + 1) exp[i]  = {WIDTH{1'b0}};
        $readmemh("golden/conv_stim.hex", stim);
        $readmemh("golden/conv_exp.hex",  exp);

        for (cse = 0; cse < N_CASES; cse = cse + 1) begin
            run_case(cse);
            if (ngot != NPIX) begin
                errors = errors + 1;
                $display("[FAIL] case %0d: collected %0d outputs (expected %0d)",
                         cse, ngot, NPIX);
            end
            for (k = 0; k < NPIX; k = k + 1) begin
                if (got[k] !== exp[cse*NPIX + k]) begin
                    errors = errors + 1;
                    if (errors <= 20)
                        $display("[FAIL] case %0d pixel %0d: got %h expected %h",
                                 cse, k, got[k], exp[cse*NPIX + k]);
                end
            end
        end

        $display("Checked %0d case(s) x %0d pixels, %0d mismatch(es).",
                 N_CASES, NPIX, errors);
        if (errors == 0) $display("RESULT: PASS");
        else             $display("RESULT: FAIL");
        $finish;
    end
endmodule
