#!/usr/bin/env python3
"""make_ppa.py -- assemble a before/after PPA table for HW4 (power homework).

Parses the Yosys area reports and the OpenSTA report_power outputs for the
baseline and clock-gated runs, then writes artifacts/ppa_compare.md with a filled
comparison table. Runs in the EDA container as part of `make compare`; it is
deliberately forgiving (missing fields become '?') so it never blocks the flow.

Usage:
  make_ppa.py <area_base.rpt> <power_base.rpt> <area_cg.rpt> <power_cg.rpt> <out.md>
"""
import re
import sys


def read(path):
    try:
        with open(path) as f:
            return f.read()
    except OSError:
        return ""


def area(text):
    """Yosys `stat -liberty` reports 'Chip area for ... : <num>' and a cell count."""
    a = re.search(r"Chip area[^:]*:\s*([0-9.]+)", text)
    n = re.search(r"Number of cells:\s*([0-9]+)", text)
    return (a.group(1) if a else "?", n.group(1) if n else "?")


def total_power(text):
    """OpenSTA report_power prints a 'Total' row: internal switching leakage total.
    Grab the last four floats on the Total line (W)."""
    m = re.search(r"^\s*Total\s+(.*)$", text, re.MULTILINE)
    if not m:
        return ("?", "?", "?", "?")
    nums = re.findall(r"[-+]?[0-9.]+(?:e[-+]?[0-9]+)?", m.group(1))
    # columns: Internal Switching Leakage Total (Power %) -> take first 4 numbers
    nums = (nums + ["?"] * 4)[:4]
    return tuple(nums)


def main():
    if len(sys.argv) != 6:
        print(__doc__)
        return 1
    ab, pb, ac, pc, out = sys.argv[1:6]

    a_base, n_base = area(read(ab))
    a_cg,   n_cg   = area(read(ac))
    pi_b, ps_b, pl_b, pt_b = total_power(read(pb))
    pi_c, ps_c, pl_c, pt_c = total_power(read(pc))

    def pct(b, c):
        try:
            b, c = float(b), float(c)
            return "%.1f%%" % (100.0 * (b - c) / b) if b else "?"
        except ValueError:
            return "?"

    md = f"""# HW4 -- IoT Data Filter: PPA before/after clock gating

> Auto-generated by `make compare` (tools/make_ppa.py). Replace the discussion
> placeholders with your own analysis before submitting.

## Power (OpenSTA `report_power`, activity-driven from the workload VCD)

| Metric (W)       | Baseline | Clock-gated | Reduction |
|------------------|----------|-------------|-----------|
| Internal power   | {pi_b} | {pi_c} | {pct(pi_b, pi_c)} |
| Switching power  | {ps_b} | {ps_c} | {pct(ps_b, ps_c)} |
| Leakage power    | {pl_b} | {pl_c} | {pct(pl_b, pl_c)} |
| **Total power**  | **{pt_b}** | **{pt_c}** | **{pct(pt_b, pt_c)}** |

## Area (Yosys `stat -liberty`)

| Metric        | Baseline | Clock-gated | Delta |
|---------------|----------|-------------|-------|
| Cell count    | {n_base} | {n_cg} | {pct(n_base, n_cg)} |
| Chip area (um^2) | {a_base} | {a_cg} | {pct(a_base, a_cg)} |

## Discussion (fill in)

- **Where did the power go?** Identify the dominant contributor in the baseline
  (clock tree vs the CRC/LFSR state registers vs the combinational units).
- **What did clock gating buy?** Explain the total-power reduction and the
  small area cost of the inserted clock-gating cells.
- **Operand isolation:** the idle units' inputs are held at 0 so their
  combinational logic does not toggle. Quantify the switching-power effect and
  contrast it with gating the sequential state (CRC/LFSR registers).
- **PPA trade-off:** clock gating typically *adds* a few cells (area up slightly)
  while cutting dynamic power -- state the numbers above and conclude.
"""
    with open(out, "w") as f:
        f.write(md)
    print("wrote", out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
