#!/usr/bin/env python3
"""Golden-vector generator + reference model for the TinyRISC-16 Q6.10 ALU (HW1).

This Python model is the SINGLE SOURCE OF TRUTH for expected ALU behavior; it
must match common/rtl/alu/alu.v exactly (WIDTH=16, FRAC=10 -> Q6.10).

Outputs (written next to this script, in ../golden/):
  alu_vectors.hex   one 64-bit packed vector per line, fields (MSB first):
                      [63:60] op   [59:44] a   [43:28] b
                      [27:12] y    [11] zero   [10] overflow   [9:0] 0
  alu_count.vh      `localparam integer N_VECTORS = <n>;`  (included by the TB)

Run:  python3 tools/gen_vectors.py     (from hw/hw1-alu/)
"""
import os
import random

WIDTH = 16
FRAC  = 10
MASK  = (1 << WIDTH) - 1
SMAX  = (1 << (WIDTH - 1)) - 1      # +32767
SMIN  = -(1 << (WIDTH - 1))        # -32768


def u16(x):
    return x & MASK


def s16(x):
    x &= MASK
    return x - (1 << WIDTH) if x & (1 << (WIDTH - 1)) else x


def sat(v):
    return SMAX if v > SMAX else (SMIN if v < SMIN else v)


# Opcodes -- must match alu_defs.vh.
ADD, SUB, AND, OR, XOR, SLL, SRL, SRA, SLT, SLTU, FXADD, FXSUB, FXMUL, PASSB = range(14)
N_OPS = 14


def model(op, a, b):
    """Return (y, zero, overflow) for one ALU operation. Mirror of alu.v."""
    A, B = s16(a), s16(b)
    ua, ub = u16(a), u16(b)
    sh = ub & 0x1F
    ovf = 0
    if op == ADD:
        y = u16(A + B)
    elif op == SUB:
        y = u16(A - B)
    elif op == AND:
        y = ua & ub
    elif op == OR:
        y = ua | ub
    elif op == XOR:
        y = ua ^ ub
    elif op == SLL:
        y = u16(ua << sh)
    elif op == SRL:
        y = u16(ua >> sh)
    elif op == SRA:
        y = u16(A >> sh)            # Python >> on signed int is arithmetic
    elif op == SLT:
        y = 1 if A < B else 0
    elif op == SLTU:
        y = 1 if ua < ub else 0
    elif op == FXADD:
        full = A + B
        ovf = int(full > SMAX or full < SMIN)
        y = u16(sat(full))
    elif op == FXSUB:
        full = A - B
        ovf = int(full > SMAX or full < SMIN)
        y = u16(sat(full))
    elif op == FXMUL:
        prod = A * B
        rnd = (prod + (1 << (FRAC - 1))) >> FRAC
        ovf = int(rnd > SMAX or rnd < SMIN)
        y = u16(sat(rnd))
    elif op == PASSB:
        y = ub
    else:
        y = 0
    return y, int(y == 0), ovf


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    outdir = os.path.join(here, "..", "golden")
    os.makedirs(outdir, exist_ok=True)

    rng = random.Random(20260603)  # deterministic
    corners = [0x0000, 0x0001, 0xFFFF, 0x7FFF, 0x8000, 0x8001, 0x0400, 0xFC00,
               0x000A, 0x0002, 0x0010, 0x00FF, 0x0100, 0x5555, 0xAAAA, 0x03FF]

    cases = []
    for op in range(N_OPS):
        for a in corners:           # directed corner cross-product
            for b in corners:
                cases.append((op, a, b))
        for _ in range(48):         # plus randomized coverage
            cases.append((op, rng.randint(0, MASK), rng.randint(0, MASK)))

    with open(os.path.join(outdir, "alu_vectors.hex"), "w") as f:
        for op, a, b in cases:
            y, z, o = model(op, a, b)
            word = ((op & 0xF) << 60) | (u16(a) << 44) | (u16(b) << 28) \
                   | (y << 12) | (z << 11) | (o << 10)
            f.write("%016x\n" % word)

    with open(os.path.join(outdir, "alu_count.vh"), "w") as f:
        f.write("// AUTO-GENERATED by tools/gen_vectors.py -- do not edit.\n")
        f.write("localparam integer N_VECTORS = %d;\n" % len(cases))

    print("Wrote %d golden vectors to %s" % (len(cases), outdir))


if __name__ == "__main__":
    main()
